[package]
name = "XLFM"
version = "1.0.0"
description = "Skater XL File Manager"
authors = ["Milky"]
edition = "2021"

[lib]
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
zip = "0.6"
anyhow = "1.0"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
tauri-plugin-os = "2"
reqwest = { version = "0.11", features = ["json"] }
directories = "4.0"
notify = "5"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
uuid = { version = "1", features = ["v4"] }
tauri-plugin-dialog = "2"
